# Generated by Django 5.1.15 on 2026-08-13 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fhir_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='', max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('family_name', models.CharField(blank=True, default='', max_length=255)),
                ('given_name', models.CharField(blank=True, default='', max_length=255)),
                ('resource', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fhir_patient',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['family_name', 'given_name'], name='fhir_patien_family__e81451_idx'), models.Index(fields=['birth_date'], name='fhir_patien_birth_d_bcf119_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fhir_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('pending', 'Pending'), ('booked', 'Booked'), ('arrived', 'Arrived'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('noshow', 'No Show'), ('entered-in-error', 'Entered in Error'), ('checked-in', 'Checked In'), ('waitlist', 'Waitlist')], max_length=32)),
                ('start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('resource', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='app.patient')),
            ],
            options={
                'db_table': 'fhir_appointment',
                'ordering': ['-start', '-created_at'],
                'indexes': [models.Index(fields=['status', 'start'], name='fhir_appoin_status_5bafc0_idx'), models.Index(fields=['patient', 'start'], name='fhir_appoin_patient_723abb_idx')],
            },
        ),
    ]
